using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Options;
using PropertyGpsApi.Common;
using PropertyGpsApi.Infrastructure.Options;
using PropertyGpsApi.Infrastructure.Security.BodyEncryption;

namespace PropertyGpsApi.Tests;

/// <summary>
/// The cross-language test vector: envelopes sealed by the app's real Dart sealer
/// (tool/make_request_encryption_vector.dart, seeded Fortuna, fixed ts, the public TEST-ONLY
/// key pair), opened here by the real RequestBodyOpener. The same file sits byte for byte in
/// both repositories; if the two implementations ever drift, this is where it shows.
///
/// A missing Fixtures/request_encryption_vector_v1.json FAILS these tests rather than skipping
/// them: a skipped cross-language check looks exactly like a passing one, so a commit that left
/// the fixture out (or an antivirus that deleted it) would otherwise go unnoticed.
///
/// Expected shape (extra fields are ignored):
///   {
///     "kid": "3c67a513d1a00e0c",
///     "testOnlyPrivateKeyPkcs8": "&lt;one line of base64 PKCS#8, or PEM&gt;",
///                                       (what the Dart tool writes; also: privateKey, privateKeyPkcs8, privateKeyB64)
///     "cases": [
///       { "name": "ward-sync", "method": "POST", "path": "/v1/api/...", "part": "body",
///         "token": "&lt;raw bearer token&gt;" | null,                     (or "tok": "&lt;16 hex&gt;" | "-")
///         "plaintext": "...", "envelope": "{\"enc\":...}" (string, or the envelope object),
///         "expect": "open" | "fail" }                                (or "ok"/"valid": true|false)
///     ]
///   }
/// A negative case may give the context it is opened with in "open": {method, path, part, token}.
/// </summary>
public class RequestEncryptionVectorTests
{
    [Fact]
    public void The_fixture_is_present()
    {
        Assert.True(File.Exists(VectorFixture.FilePath),
            "Fixtures/request_encryption_vector_v1.json is missing. It is generated by the app's " +
            "tool/make_request_encryption_vector.dart, must be byte-identical to the app's " +
            "test/fixtures/request_encryption/vector_v1.json, and must be committed with the code.");
    }

    [Fact]
    public void The_fixture_key_is_the_TEST_ONLY_key_and_is_refused_outside_Development()
    {
        var vector = VectorFixture.Load();
        Assert.True(RequestKeyMaterial.TryParse(vector.PrivateKey, out var material));
        Assert.Equal(RequestEncryptionOptions.TestOnlyKid, material.Kid);
        Assert.Equal(vector.Kid, material.Kid);
        Assert.True(material.KeySizeBits >= RequestEncryptionOptions.MinimumKeyBits);

        var options = new RequestEncryptionOptions
        {
            Mode = RequestEncryptionMode.Optional,
            Keys = new() { ["0"] = new RequestEncryptionKeyOptions { PrivateKey = vector.PrivateKey } }
        };

        var production = new RequestEncryptionOptionsValidator(new Env("Production")).Validate(null, options);
        Assert.True(production.Failed);
        Assert.Contains("TEST-ONLY", string.Join("\n", production.Failures!));

        var development = new RequestEncryptionOptionsValidator(new Env("Development")).Validate(null, options);
        Assert.True(development.Succeeded, string.Join("\n", development.Failures ?? []));
    }

    [Fact]
    public void The_fixture_has_cases_that_open_and_cases_that_must_not()
    {
        var vector = VectorFixture.Load();
        Assert.Contains(vector.Cases, c => c.ShouldOpen);
        Assert.Contains(vector.Cases, c => !c.ShouldOpen);
        Assert.All(vector.Cases.Where(c => c.ShouldOpen), c => Assert.NotNull(c.Plaintext));
    }

    [Fact]
    public void A_positive_case_has_a_wrapped_key_whose_first_byte_is_zero()
    {
        // About one seal in 256 wraps the AES key into a k that starts with 0x00. The app must
        // still send all 384 bytes, and this opener (which insists on exactly the modulus
        // length) must still open it; the vector carries one such case so both sides prove it.
        var vector = VectorFixture.Load();
        var modulusBytes = RequestKeyMaterial.TryParse(vector.PrivateKey, out var material)
            ? material.ModulusBytes
            : throw new InvalidOperationException("The fixture key does not parse.");

        var leadingZero = vector.Cases.Where(c => c.ShouldOpen).Select(c => WrappedKey(c.Envelope))
            .Where(k => k[0] == 0).ToList();

        Assert.NotEmpty(leadingZero);
        Assert.All(leadingZero, k => Assert.Equal(modulusBytes, k.Length));
    }

    private static byte[] WrappedKey(string envelope)
    {
        using var document = JsonDocument.Parse(envelope);
        return Convert.FromBase64String(document.RootElement.GetProperty("k").GetString()!);
    }

    [Fact]
    public void Every_positive_case_opens_to_its_plaintext()
    {
        var vector = VectorFixture.Load();
        var opener = vector.Opener();
        var failures = new List<string>();

        foreach (var c in vector.Cases.Where(c => c.ShouldOpen))
        {
            try
            {
                var plaintext = opener.Open(Encoding.UTF8.GetBytes(c.Envelope), c.OpenContext);
                if (plaintext != c.Plaintext) failures.Add($"{c.Name}: opened to different text");
            }
            catch (ApiException e)
            {
                failures.Add($"{c.Name}: {e.Code}");
            }
        }

        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    [Fact]
    public void Every_negative_case_fails_with_BODY_DECRYPT_FAILED()
    {
        var vector = VectorFixture.Load();
        var opener = vector.Opener();
        var failures = new List<string>();

        foreach (var c in vector.Cases.Where(c => !c.ShouldOpen))
        {
            try
            {
                opener.Open(Encoding.UTF8.GetBytes(c.Envelope), c.OpenContext);
                failures.Add($"{c.Name}: opened, but must not");
            }
            catch (ApiException e) when (e.Code != ApiErrorCodes.BodyDecryptFailed)
            {
                failures.Add($"{c.Name}: {e.Code}, expected BODY_DECRYPT_FAILED");
            }
            catch (ApiException)
            {
                // expected
            }
        }

        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    [Fact]
    public async Task Every_positive_case_with_a_raw_token_also_opens_through_the_filter()
    {
        // This is the check on tok: the filter derives it from the Authorization header itself.
        var vector = VectorFixture.Load();
        var options = vector.Options();
        var failures = new List<string>();

        foreach (var c in vector.Cases.Where(c => c.ShouldOpen && c.HasRawToken))
        {
            var log = new CapturingLogger<RequestBodyDecryptionFilter>();
            var filter = FilterHarness.Filter(options, log);
            DefaultHttpContext http;
            Microsoft.AspNetCore.Mvc.Abstractions.ParameterDescriptor parameter;

            if (c.Part == BodyEncryptionFormat.BodyPart)
            {
                http = FilterHarness.JsonRequest(c.Envelope, path: c.Path, method: c.Method, token: c.Token);
                parameter = FilterHarness.BodyParameter();
            }
            else if (c.Part.StartsWith(BodyEncryptionFormat.FormPartPrefix, StringComparison.Ordinal))
            {
                var field = c.Part[BodyEncryptionFormat.FormPartPrefix.Length..];
                http = Multipart.Request(Multipart.Build([(field, c.Envelope)]), path: c.Path, token: c.Token);
                http.Request.Method = c.Method;
                parameter = FilterHarness.FormParameter();
            }
            else
            {
                failures.Add($"{c.Name}: unknown part {c.Part}");
                continue;
            }

            try
            {
                var reached = await FilterHarness.RunAsync(filter, FilterHarness.Context(http, parameter));
                var opened = c.Part == BodyEncryptionFormat.BodyPart
                    ? await FilterHarness.ReadBodyAsync(http.Request)
                    : (await http.Request.ReadFormAsync())[c.Part[BodyEncryptionFormat.FormPartPrefix.Length..]].ToString();
                if (!reached || opened != c.Plaintext) failures.Add($"{c.Name}: did not open to its plaintext through the filter");
            }
            catch (ApiException e)
            {
                failures.Add($"{c.Name}: {e.Code} through the filter");
            }
        }

        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    private sealed class Env(string name) : IHostEnvironment
    {
        public string EnvironmentName { get; set; } = name;
        public string ApplicationName { get; set; } = "PropertyGpsApi.Tests";
        public string ContentRootPath { get; set; } = AppContext.BaseDirectory;
        public IFileProvider ContentRootFileProvider { get; set; } = new NullFileProvider();
    }
}

internal sealed record VectorCase(
    string Name,
    string Method,
    string Path,
    string Part,
    string? Token,
    bool HasRawToken,
    string TokenTag,
    string? Plaintext,
    string Envelope,
    bool ShouldOpen)
{
    public BodyAadContext OpenContext => new(Method, Path, Part, TokenTag);
}

internal sealed record VectorFixture(string Kid, string PrivateKey, IReadOnlyList<VectorCase> Cases)
{
    public static string FilePath => System.IO.Path.Combine(AppContext.BaseDirectory, "Fixtures", "request_encryption_vector_v1.json");

    public RequestEncryptionOptions Options() => new()
    {
        Mode = RequestEncryptionMode.Required,
        Keys = new() { ["0"] = new RequestEncryptionKeyOptions { PrivateKey = PrivateKey } }
    };

    public RequestBodyOpener Opener() =>
        new(new RequestKeyRing(Microsoft.Extensions.Options.Options.Create(Options())), TimeProvider.System);

    public static VectorFixture Load()
    {
        using var document = JsonDocument.Parse(File.ReadAllBytes(FilePath));
        var root = document.RootElement;

        var kid = root.GetProperty("kid").GetString()!;
        var privateKey = FirstString(root, "testOnlyPrivateKeyPkcs8", "privateKey", "privateKeyPkcs8", "privateKeyB64", "private_key")
                         ?? throw new InvalidOperationException("The vector fixture has no private key field.");

        var cases = new List<VectorCase>();
        var index = 0;
        foreach (var c in root.GetProperty("cases").EnumerateArray())
        {
            index++;
            var open = c.TryGetProperty("open", out var o) && o.ValueKind == JsonValueKind.Object ? o : c;

            var name = FirstString(c, "name") ?? $"case {index}";
            var method = FirstString(open, "method") ?? FirstString(c, "method") ?? "POST";
            var path = FirstString(open, "path") ?? FirstString(c, "path")
                       ?? throw new InvalidOperationException($"{name}: no path");
            var part = FirstString(open, "part") ?? FirstString(c, "part") ?? BodyEncryptionFormat.BodyPart;

            var (hasRawToken, token) = RawToken(open) ?? RawToken(c) ?? (false, null);
            var tokenTag = FirstString(open, "tok") ?? FirstString(c, "tok") ?? BodyEncryptionFormat.TokenTag(token);
            if (hasRawToken && tokenTag != BodyEncryptionFormat.TokenTag(token))
                throw new InvalidOperationException($"{name}: tok does not match SHA-256 of token");

            var envelopeElement = c.GetProperty("envelope");
            var envelope = envelopeElement.ValueKind == JsonValueKind.String
                ? envelopeElement.GetString()!
                : envelopeElement.GetRawText();

            var plaintext = FirstString(c, "plaintext", "plain");
            cases.Add(new VectorCase(name, method, path, part, token, hasRawToken, tokenTag, plaintext, envelope,
                ShouldOpen(c, plaintext)));
        }

        return new VectorFixture(kid, privateKey, cases);
    }

    private static (bool, string?)? RawToken(JsonElement e)
    {
        foreach (var name in new[] { "token", "bearerToken", "bearer" })
        {
            if (!e.TryGetProperty(name, out var value)) continue;
            return value.ValueKind switch
            {
                JsonValueKind.String => (true, value.GetString()),
                JsonValueKind.Null => (true, null),
                _ => null
            };
        }
        return null;
    }

    private static bool ShouldOpen(JsonElement c, string? plaintext)
    {
        if (c.TryGetProperty("expect", out var expect) && expect.ValueKind == JsonValueKind.String)
        {
            var text = expect.GetString()!.ToLowerInvariant();
            if (text is "open" or "opens" or "ok" or "success" or "pass" or "valid" or "plaintext") return true;
            if (text is "fail" or "fails" or "reject" or "error" or "invalid" or "body_decrypt_failed") return false;
            throw new InvalidOperationException($"Unknown expect value '{text}'.");
        }

        foreach (var name in new[] { "ok", "valid", "opens", "shouldOpen", "positive" })
            if (c.TryGetProperty(name, out var flag) && flag.ValueKind is JsonValueKind.True or JsonValueKind.False)
                return flag.GetBoolean();

        if (c.TryGetProperty("error", out _) || c.TryGetProperty("expectError", out _)) return false;

        return plaintext is not null;
    }

    private static string? FirstString(JsonElement e, params string[] names)
    {
        foreach (var name in names)
            if (e.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.String)
                return value.GetString();
        return null;
    }
}
